# Generated by Django 5.0.4 on 2024-11-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_note_updated_at_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
